type: object
required: [geometry, distance]
properties:
  geometry:
    allOf:
      - $ref: bblocks://ogc.geo.common.data_types.geojson
      - required: [type, coordinates]
        properties:
          type:
            enum: [Point, LineString, polygon]
  distance:
    type: object
    properties:
      type:
        type: string
        example: number
      minimum:
        type: number
        example: 0
  units:
    $ref: bblocks://ogc.ogc-utils.iri-or-curie
    enum: [ meters, kilometers, feet, miles ]
    default: meters
