allOf:
  - $ref: bblocks://ogc.api.processes.v1.schemas.outputDescription
properties:
  schema:
    type: object
    properties:
      bufferedGeometry:
        type: object
        properties:
          title:
            type: string
            const: Buffered Geometry
          description:
            type: string
          schema:
            $ref: bblocks://ogc.osc.ogcapi-processes.profiled-api.schemas.buffer-geometry.outputSchema#/properties/bufferedGeometry
      area:
        type: object
        properties:
          title:
            type: string
            const: Buffer Area
          description:
            type: string
          schema:
            $ref: bblocks://ogc.osc.ogcapi-processes.profiled-api.schemas.buffer-geometry.outputSchema#/properties/area