allOf:
  - $ref: bblocks://ogc.api.processes.v1.schemas.process
  - properties:
      inputs:
        $ref: bblocks://ogc.osc.ogcapi-processes.profiled-api.schemas.buffer-geometry.inputDescription
        additionalProperties: false
      outputs:
        $ref: bblocks://ogc.osc.ogcapi-processes.profiled-api.schemas.buffer-geometry.outputDescription
        additionalProperties: false