"$schema": https://json-schema.org/draft/2020-12/schema
description: 'EarthCode Product'
allOf:
  - $ref: bblocks://ogc.osc.geodcat-stac-earthcode.common
  - anyOf:
    - $ref: bblocks://ogc.contrib.stac.collection
    - $ref: bblocks://ogc.contrib.stac.collection-v1-0-0
